spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample_mysql_db
    username: root
    password: pwd
    driver-class-name: org.mariadb.jdbc.Driver
jdbc:
  query: select id, name, tag from test order by id
  triggerDelay: 5
spring.cloud.stream.bindings.output.destination: test-data
spring.cloud.stream.bindings.input.destination: test-data